Koperasi Simpan Pinjam/adminlte/Controllers/TransaksiPinjamanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using adminlte.Models;
using System.Data.Entity.Validation;
using pinjamanLibrary;

namespace adminlte.Controllers
{
    public class TransaksiPinjamanController : Controller
    {
        string connectionString = @"Data Source = DESKTOP-Q01413R; Initial Catalog = Koperasi; Integrated Security = True";

        [HttpGet]
        // GET: TransaksiPinjaman
        public ActionResult Index()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * From trans_pinjaman", sqlcon);

                sqlDa.Fill(dtbSimpan);
            }
            return View(dtbSimpan);

        }

        // GET: TransaksiPinjaman/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TransaksiPinjaman/Create
        public ActionResult Create()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            KoperasiEntities2 db = new KoperasiEntities2();
            List<anggota> list = db.anggotas.ToList();
            List<pinjaman> list1 = db.pinjamen.ToList();
            ViewBag.anggotaList = new SelectList(list, "no_anggota", "nama_ang");
            ViewBag.pinjamanList = new SelectList(list1, "kd_pinj", "jns_pinj");

            return View();
        }

        // POST: TransaksiPinjaman/Create
        [HttpPost]
        public ActionResult Create(TransaksiPinjamanModel pinjam)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                DataTable dtbSimpan = new DataTable();
                sqlcon.Open();
                KoperasiEntities2 db = new KoperasiEntities2();
                List<anggota> list = db.anggotas.ToList();
                List<pinjaman> list1 = db.pinjamen.ToList();
                ViewBag.anggotaList = new SelectList(list, "no_anggota", "nama_ang");
                ViewBag.pinjamanList = new SelectList(list1, "kd_pinj", "jns_pinj");

                string query = "SELECT bunga FROM pinjaman where kd_pinj = @kd_pinj";
                SqlDataAdapter sqlCmd = new SqlDataAdapter(query, sqlcon);
                sqlCmd.SelectCommand.Parameters.AddWithValue("@kd_pinj", pinjam.kd_pinj);
                sqlCmd.Fill(dtbSimpan);


                trans_pinjaman tpinjam = new trans_pinjaman();
                Peminjaman objpinjam = new Peminjaman();
                var bunga = Convert.ToDouble(dtbSimpan.Rows[0][0].ToString());
                var jumlah = pinjam.jlh;

                var bungaTot = objpinjam.totalPeminjaman(bunga , jumlah);
                var total = bungaTot + jumlah;
                var angsuran = total / pinjam.lama;
                tpinjam.no_ang = pinjam.no_ang;
                tpinjam.jlh = pinjam.jlh;
                tpinjam.keterangan = pinjam.keterangan;
                tpinjam.lama = pinjam.lama;
                tpinjam.bunga= Convert.ToDouble(dtbSimpan.Rows[0][0].ToString());
                tpinjam.status = "Belum Lunas";
                tpinjam.kd_pinj = pinjam.kd_pinj;
                tpinjam.tglpinj = pinjam.tglpinj;
                tpinjam.total = total;
                tpinjam.angsuran = angsuran;

                db.trans_pinjaman.Add(tpinjam);

                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult UbahStatus(int id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query2 = "UPDATE trans_pinjaman SET status=@status Where no_pinj = @no_pinj";
                SqlCommand sqlCmd2 = new SqlCommand(query2, sqlcon);
                sqlCmd2.Parameters.AddWithValue("@no_pinj", id);
                sqlCmd2.Parameters.AddWithValue("@status", "Lunas");
                sqlCmd2.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: TransaksiPinjaman/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            KoperasiEntities2 db = new KoperasiEntities2();
            List<anggota> list = db.anggotas.ToList();
            List<pinjaman> list1 = db.pinjamen.ToList();
            ViewBag.anggotaList = new SelectList(list, "no_anggota", "nama_ang");
            ViewBag.pinjamanList = new SelectList(list1, "kd_pinj", "jns_pinj");

            TransaksiPinjamanModel Tpinjam = new TransaksiPinjamanModel();
            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "SELECT * FROM trans_pinjaman where no_pinj = @no_pinj";
                SqlDataAdapter sqlCmd = new SqlDataAdapter(query, sqlcon);
                sqlCmd.SelectCommand.Parameters.AddWithValue("@no_pinj", id);
                sqlCmd.Fill(dtbSimpan);
            }
            if (dtbSimpan.Rows.Count == 1)
            {
                Tpinjam.no_pinj = Convert.ToInt32(dtbSimpan.Rows[0][0].ToString());
                Tpinjam.tglpinj = Convert.ToDateTime(dtbSimpan.Rows[0][1].ToString());
                Tpinjam.bunga = Convert.ToDouble(dtbSimpan.Rows[0][2].ToString());
                Tpinjam.jlh = Convert.ToDouble(dtbSimpan.Rows[0][3].ToString());
                Tpinjam.total = Convert.ToDouble(dtbSimpan.Rows[0][4].ToString());
                Tpinjam.angsuran = Convert.ToDouble(dtbSimpan.Rows[0][5].ToString());
                Tpinjam.status = dtbSimpan.Rows[0][6].ToString();
                Tpinjam.kd_pinj = dtbSimpan.Rows[0][7].ToString();
                Tpinjam.no_ang = dtbSimpan.Rows[0][8].ToString();
                Tpinjam.keterangan= dtbSimpan.Rows[0][9].ToString();
                Tpinjam.lama = Convert.ToDouble(dtbSimpan.Rows[0][10].ToString());

                return View(Tpinjam);
            }
            else
                return RedirectToAction("Index");


        }

        // POST: TransaksiPinjaman/Edit/5
        [HttpPost]
        public ActionResult Edit(TransaksiPinjamanModel pinjam)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            KoperasiEntities2 db = new KoperasiEntities2();
            List<anggota> list = db.anggotas.ToList();
            List<pinjaman> list1 = db.pinjamen.ToList();
            ViewBag.anggotaList = new SelectList(list, "no_anggota", "nama_ang");
            ViewBag.pinjamanList = new SelectList(list1, "kd_pinj", "jns_pinj");

            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                DataTable dtbSimpan = new DataTable();
                sqlcon.Open();

                string query2 = "SELECT bunga FROM pinjaman where kd_pinj = @kd_pinj";
                SqlDataAdapter sqlCmd2 = new SqlDataAdapter(query2, sqlcon);
                sqlCmd2.SelectCommand.Parameters.AddWithValue("@kd_pinj", pinjam.kd_pinj);
                sqlCmd2.Fill(dtbSimpan);

                var total = (Convert.ToDouble(dtbSimpan.Rows[0][0].ToString()) * pinjam.jlh) / 100;
                var angsuran = total / pinjam.lama;

                string query = "UPDATE trans_pinjaman SET tglpinj=@tglpinj, bunga=@bunga, jlh=@jlh, total=@total, angsuran=@angsuran, status=@status, kd_pinj=@kd_pinj, no_ang=@no_ang, keterangan=@keterangan, lama=@lama Where no_pinj = @no_pinj";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                
                sqlCmd.Parameters.AddWithValue("@no_pinj", pinjam.no_pinj);
                sqlCmd.Parameters.AddWithValue("@tglpinj", pinjam.tglpinj);
                sqlCmd.Parameters.AddWithValue("@bunga", Convert.ToDouble(dtbSimpan.Rows[0][0].ToString()));
                sqlCmd.Parameters.AddWithValue("@jlh", pinjam.jlh);
                sqlCmd.Parameters.AddWithValue("@total", total);
                sqlCmd.Parameters.AddWithValue("@angsuran", angsuran);
                sqlCmd.Parameters.AddWithValue("@status", "Belum Lunas");
                sqlCmd.Parameters.AddWithValue("@kd_pinj", pinjam.kd_pinj);
                sqlCmd.Parameters.AddWithValue("@no_ang", pinjam.no_ang);
                sqlCmd.Parameters.AddWithValue("@keterangan", pinjam.keterangan);
                sqlCmd.Parameters.AddWithValue("@lama", pinjam.lama);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: TransaksiPinjaman/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                string query = "DELETE FROM trans_pinjaman Where no_pinj = @no_pinj";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                sqlCmd.Parameters.AddWithValue("@no_pinj", id);
                sqlCmd.ExecuteNonQuery();
            }

Koperasi Simpan Pinjam/adminlte/Views/TransaksiPinjaman/Create.cshtml
@model adminlte.Models.TransaksiPinjamanModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Tambah Transaksi Pinjaman
            <small>Koperasi</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Pinjam</a></li>
            <li class="active">Form Transaksi Pinjaman</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <label>Nama Anggota</label>
                                @Html.DropDownListFor(model => model.no_ang, ViewBag.anggotaList as SelectList, "--Pilih Anggota--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.no_ang, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Tanggal Pinjam</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.tglpinj, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker", @type = "text" } })
                                    @Html.ValidationMessageFor(model => model.tglpinj, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Jenis Pinjaman</label>
                                @Html.DropDownListFor(model => model.kd_pinj, ViewBag.pinjamanList as SelectList, "--Jenis Pinjaman--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kd_pinj, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Jumlah Peminjaman</label>
                                @Html.EditorFor(model => model.jlh, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.jlh, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Lama Angsuran (bulan)</label>
                                @Html.EditorFor(model => model.lama, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.lama, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Keterangan</label>
                                @Html.EditorFor(model => model.keterangan, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.keterangan, "", new { @class = "text-danger" })
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Tambah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

@section Scripts
{
    <script type="text/javascript">
            $(document).ready(function () {
                //Date picker
                $('#datepicker').datepicker({
                    autoclose: true
                })
            })
    </script>
}

Koperasi Simpan Pinjam/adminlte/Views/TransaksiPinjaman/Edit.cshtml
@model adminlte.Models.TransaksiPinjamanModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Tambah Transaksi Pinjaman
            <small>Koperasi</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Pinjam</a></li>
            <li class="active">Form Transaksi Pinjaman</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.no_pinj)

                            <div class="form-group">
                                <label>Nama Anggota</label>
                                @Html.DropDownListFor(model => model.no_ang, ViewBag.anggotaList as SelectList, "--Pilih Anggota--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.no_ang, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Tanggal Pinjam</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.tglpinj, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker", @type = "text" } })
                                    @Html.ValidationMessageFor(model => model.tglpinj, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Jenis Pinjaman</label>
                                @Html.DropDownListFor(model => model.kd_pinj, ViewBag.pinjamanList as SelectList, "--Jenis Pinjaman--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kd_pinj, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Jumlah Peminjaman</label>
                                @Html.EditorFor(model => model.jlh, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.jlh, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Lama Angsuran (bulan)</label>
                                @Html.EditorFor(model => model.lama, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.lama, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Keterangan</label>
                                @Html.EditorFor(model => model.keterangan, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.keterangan, "", new { @class = "text-danger" })
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Ubah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

@section Scripts
{
    <script type="text/javascript">
            $(document).ready(function () {
                //Date picker
                $('#datepicker').datepicker({
                    autoclose: true
                })
            })
    </script>
}

Koperasi Simpan Pinjam/adminlte/Views/TransaksiPinjaman/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Transaksi Pinjaman
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Pinjam</a></li>
            <li class="active">Transaksi</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Data Transaksi Pinjaman</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nomor Anggota</th>
                                    <th>Tanggal Pinjam</th>
                                    <th>Angsuran/Bulan</th>
                                    <th>Total Pinjam</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Rows.Count == 0)
                                {
                                    <tr>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                    </tr>
                                }
                                else
                                {
                                    for (int i = 0; i < Model.Rows.Count; i++)
                                    {
                                        using (Html.BeginForm("Delete", "RepFilters", new { @id = Model.Rows[i][0] }))
                                        {
                                            var myModal = "myModal" + Model.Rows[i][0];
                                            <tr>
                                                <td>@Model.Rows[i][8]</td>
                                                <td>@(((DateTime)Model.Rows[i][1]).ToString("dd MMMM yyyy"))</td>
                                                <td style="text-align:right">Rp.@Model.Rows[i][5]</td>
                                                <td style="text-align:right">Rp.@Model.Rows[i][4]</td>
                                                <td><label class="btn bg-maroon disabled">@Model.Rows[i][6]</label></td>
                                            
                                                <td>
                                                    @if (@Model.Rows[i][6] == "Belum Lunas")
                                                    {
                                                        <a href="@Url.Action("Edit", "TransaksiPinjaman", new { @id = Model.Rows[i][0] })" class="btn btn-app btn-xs bg-blue"><i class="fa fa-edit"></i>Ubah</a>
                                                        <a href="" class="btn btn-app btn-xs bg-red" data-toggle="modal" data-target="#@myModal" data-whatever="@Model.Rows[i][0]" ><i class="fa fa-trash"></i>Hapus</a>
                                                        <a href="@Url.Action("UbahStatus", "TransaksiPinjaman", new { @id = Model.Rows[i][0] })" class="btn btn-app btn-xs bg-aqua"><i class="fa fa-check"></i>Lunas</a>
                                                    }
                                                    else
                                                    {
                                                        <a href="" class="btn btn-app btn-xs bg-red" data-toggle="modal" data-target="#@myModal" data-whatever="@Model.Rows[i][0]"><i class="fa fa-trash"></i>Hapus</a>
                                                        <a href="#" class="btn btn-app btn-xs bg-gray disabled"><i class="fa fa-check"></i>Lunas</a>
                                                    }

                                                    <div class="modal fade" id="@myModal">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                    <h4 class="modal-title">Alert Modal</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Apakah anda yakin untuk menghapus data @Model.Rows[i][0]?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Tidak</button>
                                                                    <a href="@Url.Action("Delete", "TransaksiPinjaman", new { @id = Model.Rows[i][0] })" class="btn btn-primary">Ya</a>
                                                                </div>
                                                            </div>
                                                            <!-- /.modal-content -->
                                                        </div>
                                                        <!-- /.modal-dialog -->
                                                    </div>
                                                    <!-- /.modal -->
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>

                        <a href="@Url.Action("Create", "TransaksiPinjaman")" class="btn btn-success">Tambah Data</a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
</div>

@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}