Koperasi Simpan Pinjam/adminlte/Controllers/DSimpanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using adminlte.Models;

namespace adminlte.Controllers
{
    public class DSimpanController : Controller
    {
        string connectionString = @"Data Source = DESKTOP-Q01413R; Initial Catalog = Koperasi; Integrated Security = True";
        // GET: DSimpan
        public ActionResult Index()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * From view_simpanan", sqlcon);
                sqlDa.Fill(dtbSimpan);
            }
            return View(dtbSimpan);
        }

        // GET: DSimpan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DSimpan/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DSimpan/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DSimpan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DSimpan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: DSimpan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DSimpan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Koperasi Simpan Pinjam/adminlte/Controllers/TransaksiSimpananController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using adminlte.Models;
using System.Data.Entity.Validation;

namespace adminlte.Controllers
{
    public class TransaksiSimpananController : Controller
    {
        string connectionString = @"Data Source = DESKTOP-Q01413R; Initial Catalog = Koperasi; Integrated Security = True";

        [HttpGet]
        // GET: TransaksiSimpanan
        public ActionResult Index()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * From trans_simpanan", sqlcon);
                sqlDa.Fill(dtbSimpan);
            }
            return View(dtbSimpan);
        }

        // GET: TransaksiSimpanan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult DSimpan()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * From view_simpanan", sqlcon);
                sqlDa.Fill(dtbSimpan);
            }
            return View(dtbSimpan);
        }

        // GET: TransaksiSimpanan/Create
        public ActionResult Create()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            KoperasiEntities2 db = new KoperasiEntities2();
            List<anggota> list2 = db.anggotas.ToList();
            List<simpanan> list1 = db.simpanans.ToList();
            ViewBag.anggotaList2 = new SelectList(list2, "no_anggota", "nama_ang");
            ViewBag.simpananList = new SelectList(list1, "kd_simp", "jns_simp");

            return View();
        }

        // POST: TransaksiSimpanan/Create
        [HttpPost]
        public ActionResult Create(TransaksiSimpananModel simpan)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                DataTable dtbSimpan = new DataTable();
                sqlcon.Open();

                KoperasiEntities2 db = new KoperasiEntities2();
                AnggotaModel anggota = new AnggotaModel();
                List<anggota> list = db.anggotas.ToList();
                List<simpanan> list1 = db.simpanans.ToList();
                ViewBag.anggotaList = new SelectList(list, "no_anggota", "nama_ang");
                ViewBag.anggotaList1 = new SelectList(list, "no_simp", "nama_ang");
                ViewBag.simpananList = new SelectList(list1, "kd_simp", "jns_simp");

                string query = "SELECT no_simp FROM anggota where no_anggota = @no_anggota";
                SqlDataAdapter sqlCmd = new SqlDataAdapter(query, sqlcon);
                sqlCmd.SelectCommand.Parameters.AddWithValue("@no_anggota", simpan.no_ang);
                sqlCmd.Fill(dtbSimpan);


                trans_simpanan tsimpan = new trans_simpanan();
                tsimpan.no_ang = simpan.no_ang;
                tsimpan.tglsimpan = simpan.tglsimpan;
                tsimpan.jenis = simpan.jenis;
                tsimpan.saldo = simpan.saldo;
                tsimpan.no_simpan = dtbSimpan.Rows[0][0].ToString();
                db.trans_simpanan.Add(tsimpan);
                db.SaveChanges();        
                

            }

            return RedirectToAction("Index");
        }

        // GET: TransaksiSimpanan/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            TransaksiSimpananModel Tsimpan = new TransaksiSimpananModel();
            DataTable dtbSimpan = new DataTable();

            KoperasiEntities2 db = new KoperasiEntities2();
            List<anggota> list2 = db.anggotas.ToList();
            List<simpanan> list1 = db.simpanans.ToList();
            ViewBag.anggotaList2 = new SelectList(list2, "no_anggota", "nama_ang");
            ViewBag.simpananList = new SelectList(list1, "kd_simp", "jns_simp");

            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "SELECT * FROM trans_simpanan where id_tsimpan = @id_tsimpan";
                SqlDataAdapter sqlCmd = new SqlDataAdapter(query, sqlcon);
                sqlCmd.SelectCommand.Parameters.AddWithValue("@id_tsimpan", id);
                sqlCmd.Fill(dtbSimpan);
            }
            if (dtbSimpan.Rows.Count == 1)
            {
                Tsimpan.id_tsimpan = Convert.ToInt32(dtbSimpan.Rows[0][0].ToString());
                Tsimpan.no_simpan = dtbSimpan.Rows[0][1].ToString();
                Tsimpan.tglsimpan = Convert.ToDateTime(dtbSimpan.Rows[0][2].ToString());
                Tsimpan.jenis = dtbSimpan.Rows[0][3].ToString();
                Tsimpan.saldo = Convert.ToDouble(dtbSimpan.Rows[0][4].ToString());
                Tsimpan.no_ang = dtbSimpan.Rows[0][5].ToString();

                return View(Tsimpan);
            }
            else
                return RedirectToAction("Index");
            
        }

        // POST: TransaksiSimpanan/Edit/5
        [HttpPost]
        public ActionResult Edit(TransaksiSimpananModel simpan)
        {
            KoperasiEntities2 db = new KoperasiEntities2();
            List<anggota> list2 = db.anggotas.ToList();
            List<simpanan> list1 = db.simpanans.ToList();
            ViewBag.anggotaList2 = new SelectList(list2, "no_anggota", "nama_ang");
            ViewBag.simpananList = new SelectList(list1, "kd_simp", "jns_simp");

            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                string query = "UPDATE trans_simpanan SET no_simpan=@no_simpan, no_ang = @no_ang, tglsimpan=@tglsimpan, jenis=@jenis, saldo=@saldo Where id_tsimpan = @id_tsimpan";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                sqlCmd.Parameters.AddWithValue("@id_tsimpan", simpan.id_tsimpan);
                sqlCmd.Parameters.AddWithValue("@no_simpan", simpan.no_simpan);
                sqlCmd.Parameters.AddWithValue("@tglsimpan", simpan.tglsimpan);
                sqlCmd.Parameters.AddWithValue("@jenis", simpan.jenis);
                sqlCmd.Parameters.AddWithValue("@saldo", simpan.saldo);
                sqlCmd.Parameters.AddWithValue("@no_ang", simpan.no_ang);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: TransaksiSimpanan/Delete/5
        public ActionResult Delete(int id)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                string query = "DELETE FROM trans_simpanan Where id_tsimpan = @id_tsimpan";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                sqlCmd.Parameters.AddWithValue("@id_tsimpan", id);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");

        }

        // POST: TransaksiSimpanan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Koperasi Simpan Pinjam/adminlte/Views/TransaksiSimpanan/Create.cshtml
@model adminlte.Models.TransaksiSimpananModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Tambah Transaksi Simpanan
            <small>Koperasi</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Simpan</a></li>
            <li class="active">Form Transaksi Simpanan</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <label>Nama Anggota</label>
                                @Html.DropDownListFor(model => model.no_ang, ViewBag.anggotaList2 as SelectList, "--Pilih Anggota--", new {htmlAttributes = new { @class = "form-control" }})
                                @Html.ValidationMessageFor(model => model.no_ang, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Tanggal Simpanan</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.tglsimpan, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker", @type= "text" } })
                                    @Html.ValidationMessageFor(model => model.tglsimpan, "", new { @class = "text-danger" })
                                </div>
                             </div>
                            <!-- /.form-group -->

                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Jenis Simpanan</label>
                                @Html.DropDownListFor(model => model.jenis, ViewBag.simpananList as SelectList, "--Jenis Simpanan--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.jenis, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Saldo</label>
                                @Html.EditorFor(model => model.saldo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.saldo, "", new { @class = "text-danger" })
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Tambah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

@section Scripts
{
        <script type="text/javascript">
            $(document).ready(function () {
                //Date picker
                $('#datepicker').datepicker({
                    autoclose: true
                })
            })

        </script>
    }

Koperasi Simpan Pinjam/adminlte/Views/TransaksiSimpanan/DSimpan.cshtml
@{
    ViewBag.Title = "DSimpan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Detail Simpanan
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Simpan</a></li>
            <li class="active">Detail</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Data Detail Simpanan</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nomor Anggota</th>
                                    <th>Debet</th>
                                    <th>Kredit</th>
                                    <th>Saldo</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Rows.Count == 0)
                                {
                                    <tr>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                    </tr>
                                }
                                else
                                {
                                    for (int i = 0; i < Model.Rows.Count; i++)
                                    {
                                        <tr>
                                            <td>@Model.Rows[i][0]</td>
                                            <td style="text-align:right">Rp.@Model.Rows[i][1]</td>
                                            <td style="text-align:right">Rp.@Model.Rows[i][2]</td>
                                            <td style="text-align:right">Rp.@Model.Rows[i][3]</td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
</div>

@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}

Koperasi Simpan Pinjam/adminlte/Views/TransaksiSimpanan/Edit.cshtml
@model adminlte.Models.TransaksiSimpananModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Tambah Transaksi Simpanan
            <small>Koperasi</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Simpan</a></li>
            <li class="active">Form Transaksi Simpanan</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.id_tsimpan)
                            @Html.HiddenFor(model => model.no_simpan)
                            <div class="form-group">
                                <label>Nama Anggota</label>
                                @Html.DropDownListFor(model => model.no_ang, ViewBag.anggotaList2 as SelectList, "--Pilih Anggota--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.no_ang, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Tanggal Simpanan</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    @Html.EditorFor(model => model.tglsimpan, new { htmlAttributes = new { @class = "form-control pull-right", @id = "datepicker", @type = "text" } })
                                    @Html.ValidationMessageFor(model => model.tglsimpan, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Jenis Simpanan</label>
                                @Html.DropDownListFor(model => model.jenis, ViewBag.simpananList as SelectList, "--Jenis Simpanan--", new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.jenis, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Saldo</label>
                                @Html.EditorFor(model => model.saldo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.saldo, "", new { @class = "text-danger" })
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Ubah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

@section Scripts
{
    <script type="text/javascript">
            $(document).ready(function () {
                //Date picker
                $('#datepicker').datepicker({
                    autoclose: true
                })
            })
    </script>
}

Koperasi Simpan Pinjam/adminlte/Views/TransaksiSimpanan/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Transaksi Simpanan
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Simpan</a></li>
            <li class="active">Transaksi</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Data Transaksi Simpanan</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nomor Simpanan</th>
                                    <th>Nomor Anggota</th>
                                    <th>Tanggal Simpan</th>
                                    <th>Jenis Simpanan</th>
                                    <th>Saldo</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Rows.Count == 0)
                                {
                                    <tr>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                    </tr>
                                }
                                else
                                {

                                    for (int i = 0; i < Model.Rows.Count; i++)
                                    {
                                        using (Html.BeginForm("Delete", "RepFilters", new { @id = Model.Rows[i][0] }))
                                        {
                                            var myModal = "myModal" + Model.Rows[i][0];
                                            <tr>
                                                
                                                <td>@Model.Rows[i][1]</td>
                                                <td>@Model.Rows[i][5]</td>
                                                <td>@(((DateTime)Model.Rows[i][2]).ToString("dd MMMM yyyy"))</td>
                                                <td>@Model.Rows[i][3]</td>
                                                <td style="text-align:right">Rp.@Model.Rows[i][4]</td>
                                                <td>
                                                    <a href="@Url.Action("Edit", "TransaksiSimpanan", new { @id = Model.Rows[i][0] })" class="btn btn-app btn-xs bg-blue"><i class="fa fa-edit"></i>Ubah</a>
                                                    <a href="" class="btn btn-app btn-xs bg-red" data-toggle="modal" data-target="#@myModal" data-whatever="@Model.Rows[i][0]"><i class="fa fa-trash" ></i>Hapus</a>

                                                    <div class="modal fade" id="@myModal">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                    <h4 class="modal-title">Alert Modal</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Apakah anda yakin untuk menghapus data @Model.Rows[i][1]?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Tidak</button>
                                                                    <a href="@Url.Action("Delete", "TransaksiSimpanan", new { @id = Model.Rows[i][0] })" class="btn btn-primary">Ya</a>
                                                                </div>
                                                            </div>
                                                            <!-- /.modal-content -->
                                                        </div>
                                                        <!-- /.modal-dialog -->
                                                    </div>
                                                    <!-- /.modal -->
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>

                        <a href="@Url.Action("Create", "TransaksiSimpanan")" class="btn btn-success">Tambah Data</a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
     </section>
</div>

@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}