Koperasi Simpan Pinjam/adminlte/Models/pinjaman.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pinjaman
    {
        public int kd_pinj { get; set; }
        public string jns_pinj { get; set; }
        public Nullable<double> max_pinj { get; set; }
        public Nullable<double> max_ang { get; set; }
        public Nullable<double> bunga { get; set; }
    }
}

Koperasi Simpan Pinjam/adminlte/Controllers/PinjamanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using adminlte.Models;

namespace adminlte.Controllers
{
    public class PinjamanController : Controller
    {
        string connectionString = @"Data Source = DESKTOP-Q01413R; Initial Catalog = Koperasi; Integrated Security = True";


        [HttpGet]
        // GET: Pinjaman
        public ActionResult Index()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            DataTable dtbPinjam = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * From pinjaman", sqlcon);
                sqlDa.Fill(dtbPinjam);
            }
            return View(dtbPinjam);
        }

        // GET: Pinjaman/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pinjaman/Create
        public ActionResult Create()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Pinjaman/Create
        [HttpPost]
        public ActionResult Create(PinjamanModel pinjam)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                string query = "INSERT INTO pinjaman VALUES(@jns_pinj, @max_pinj, @max_ang, @bunga)";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                sqlCmd.Parameters.AddWithValue("@jns_pinj", pinjam.jns_pinj);
                sqlCmd.Parameters.AddWithValue("@max_pinj", pinjam.max_pinj);
                sqlCmd.Parameters.AddWithValue("@max_ang", pinjam.max_ang);
                sqlCmd.Parameters.AddWithValue("@bunga", pinjam.bunga);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: Pinjaman/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            PinjamanModel pinjam = new PinjamanModel();
            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "SELECT * FROM pinjaman where kd_pinj = @kd_pinj";
                SqlDataAdapter sqlCmd = new SqlDataAdapter(query, sqlcon);
                sqlCmd.SelectCommand.Parameters.AddWithValue("@kd_pinj", id);
                sqlCmd.Fill(dtbSimpan);
            }
            if (dtbSimpan.Rows.Count == 1)
            {
                pinjam.kd_pinj = dtbSimpan.Rows[0][0].ToString();
                pinjam.jns_pinj = dtbSimpan.Rows[0][1].ToString();
                pinjam.max_pinj = Convert.ToDouble(dtbSimpan.Rows[0][2].ToString());
                pinjam.max_ang = Convert.ToDouble(dtbSimpan.Rows[0][3].ToString());
                pinjam.bunga = Convert.ToDouble(dtbSimpan.Rows[0][4].ToString());

                return View(pinjam);
            }
            else
                return RedirectToAction("Index");
        }

        // POST: Pinjaman/Edit/5
        [HttpPost]
        public ActionResult Edit(PinjamanModel pinjam)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "UPDATE pinjaman SET jns_pinj=@jns_pinj, max_pinj=@max_pinj, max_ang=@max_ang, bunga=@bunga Where kd_pinj = @kd_pinj";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Parameters.AddWithValue("@kd_pinj", pinjam.kd_pinj);
                sqlCmd.Parameters.AddWithValue("@jns_pinj", pinjam.jns_pinj);
                sqlCmd.Parameters.AddWithValue("@max_pinj", pinjam.max_pinj);
                sqlCmd.Parameters.AddWithValue("@max_ang", pinjam.max_ang);
                sqlCmd.Parameters.AddWithValue("@bunga", pinjam.bunga);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: Pinjaman/Delete/5
        public ActionResult Delete(int id)
        {
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                string query = "DELETE FROM pinjaman Where kd_pinj = @kd_pinj";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                sqlCmd.Parameters.AddWithValue("@kd_pinj", id);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // POST: Pinjaman/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Koperasi Simpan Pinjam/adminlte/Views/Pinjaman/Create.cshtml
@model adminlte.Models.PinjamanModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Tambah Pinjaman
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-database"></i> Data Master</a></li>
            <li class="active">Form Pinjaman</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "help - block" })
                            <div class="form-group">
                                <label>Jenis Pinjaman</label>
                                @Html.EditorFor(model => model.jns_pinj, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.jns_pinj, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label>Maksimum Pinjaman</label>
                                @Html.EditorFor(model => model.max_pinj, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.max_pinj, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label>Maksimum Angsuran</label>
                                @Html.EditorFor(model => model.max_ang, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.max_ang, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label>Bunga %</label>
                                @Html.EditorFor(model => model.bunga, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.bunga, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Tambah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

Koperasi Simpan Pinjam/adminlte/Views/Pinjaman/Edit.cshtml
@model adminlte.Models.PinjamanModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Ubah Pinjaman
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-database"></i> Data Master</a></li>
            <li class="active">Form Pinjaman</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "help - block" })
                            @Html.HiddenFor(model => model.kd_pinj)
                            <div class="form-group">
                                <label>Jenis Pinjaman</label>
                                @Html.EditorFor(model => model.jns_pinj, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.jns_pinj, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label>Maksimum Pinjaman</label>
                                @Html.EditorFor(model => model.max_pinj, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.max_pinj, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label>Maksimum Angsuran</label>
                                @Html.EditorFor(model => model.max_ang, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.max_ang, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <label>Bunga %</label>
                                @Html.EditorFor(model => model.bunga, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.bunga, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Ubah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

Koperasi Simpan Pinjam/adminlte/Views/Pinjaman/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Data Pinjaman
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Data Master</a></li>
            <li class="active">Pinjaman</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <i class="fa fa-google-wallet bg-maroon"></i><h3 class="box-title">Simpanan</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Kode Pinjaman</th>
                                    <th>Jenis Pinjaman</th>
                                    <th>Maksimum Pinjaman</th>
                                    <th>Maksimum Angsur</th>
                                    <th>Bunga</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Rows.Count == 0)
                                {
                                    <tr>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                        <td>#</td>
                                    </tr>
                                }
                                else
                                {
                                    for (int i = 0; i < Model.Rows.Count; i++)
                                    {
                                        using (Html.BeginForm("Delete", "RepFilters", new { @id = Model.Rows[i][0] }))
                                        {
                                            var myModal = "myModal" + Model.Rows[i][0];
                                            <tr>
                                                <td>@Model.Rows[i][0]</td>
                                                <td>@Model.Rows[i][1]</td>
                                                <td style="text-align:right">Rp.@Model.Rows[i][2]</td>
                                                <td>@Model.Rows[i][3]</td>
                                                <td>@Model.Rows[i][4]%</td>
                                                <td>
                                                    <a href="@Url.Action("Edit", "Pinjaman", new { @id = Model.Rows[i][0] })" class="btn btn-app btn-xs bg-blue"><i class="fa fa-edit"></i>Ubah</a>
                                                    <a href="" class="btn btn-app btn-xs bg-red"  data-toggle="modal" data-target="#@myModal" data-whatever="@Model.Rows[i][0]"><i class="fa fa-trash"></i>Hapus</a>

                                                    <div class="modal fade" id="@myModal">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                    <h4 class="modal-title">Alert Modal</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Apakah anda yakin untuk menghapus data @Model.Rows[i][0]?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Tidak</button>
                                                                    <a href="@Url.Action("Delete", "Pinjaman", new { @id = Model.Rows[i][0] })" class="btn btn-primary">Ya</a>
                                                                </div>
                                                            </div>
                                                            <!-- /.modal-content -->
                                                        </div>
                                                        <!-- /.modal-dialog -->
                                                    </div>
                                                    <!-- /.modal -->
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                        <a href="@Url.Action("Create", "Pinjaman")" class="btn btn-success">Tambah Data</a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
</div>

@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}