Koperasi Simpan Pinjam/adminlte/Models/anggota.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adminlte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anggota
    {
        public string no_anggota { get; set; }
        public string nama_ang { get; set; }
        public string alamat { get; set; }
        public string kota { get; set; }
        public string no_telp { get; set; }
        public string pekerjaan { get; set; }
        public string no_simp { get; set; }
    }
}

Koperasi Simpan Pinjam/adminlte/Controllers/AnggotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using adminlte.Models;
using randomNumberLibrary;

namespace adminlte.Controllers
{
    public class AnggotaController : Controller
    {
        string connectionString = @"Data Source = DESKTOP-Q01413R; Initial Catalog = Koperasi; Integrated Security = True";

        [HttpGet]
        // GET: Anggota
        public ActionResult Index()
        {
            if(Session["id"]== null)
            {
                return RedirectToAction("Index", "Login");
            }
            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * From anggota", sqlcon);
                sqlDa.Fill(dtbSimpan);
            }
            return View(dtbSimpan);
        }

        // GET: Anggota/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Anggota/Create
        public ActionResult Create()
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: Anggota/Create
        [HttpPost]
        public ActionResult Create(AnggotaModel anggota)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                string query = "INSERT INTO anggota VALUES(@no_anggota, @nama_ang, @alamat, @kota, @no_telp, @pekerjaan, @no_simp)";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                RandomNumber objrandom = new RandomNumber();
                var id = objrandom.generateNumber("KSP");
                var kds = objrandom.generateNumber("SPN");
                sqlCmd.Parameters.AddWithValue("@no_anggota", id);
                sqlCmd.Parameters.AddWithValue("@nama_ang", anggota.nama_ang);
                sqlCmd.Parameters.AddWithValue("@alamat", anggota.alamat);
                sqlCmd.Parameters.AddWithValue("@kota", anggota.kota);
                sqlCmd.Parameters.AddWithValue("@no_telp", anggota.no_telp);
                sqlCmd.Parameters.AddWithValue("@pekerjaan", anggota.pekerjaan);
                sqlCmd.Parameters.AddWithValue("@no_simp", kds);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: Anggota/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            AnggotaModel anggota = new AnggotaModel();
            DataTable dtbSimpan = new DataTable();
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "SELECT * FROM anggota where no_anggota = @no_anggota";
                SqlDataAdapter sqlCmd = new SqlDataAdapter(query, sqlcon);
                sqlCmd.SelectCommand.Parameters.AddWithValue("@no_anggota", id);
                sqlCmd.Fill(dtbSimpan);
            }
            if (dtbSimpan.Rows.Count == 1)
            {
                anggota.no_anggota = dtbSimpan.Rows[0][0].ToString();
                anggota.nama_ang = dtbSimpan.Rows[0][1].ToString();
                anggota.alamat = dtbSimpan.Rows[0][2].ToString();
                anggota.kota = dtbSimpan.Rows[0][3].ToString();
                anggota.no_telp = dtbSimpan.Rows[0][4].ToString();
                anggota.pekerjaan = dtbSimpan.Rows[0][5].ToString();
                anggota.no_simp = dtbSimpan.Rows[0][6].ToString();

                return View(anggota);
            }
            else
                return RedirectToAction("Index");
        }

        // POST: Anggota/Edit/5
        [HttpPost]
        public ActionResult Edit(AnggotaModel anggota)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {
                sqlcon.Open();
                string query = "UPDATE anggota SET no_anggota=@no_anggota, no_simp=@no_simp, nama_ang=@nama_ang, alamat=@alamat, kota=@kota, no_telp=@no_telp, pekerjaan=@pekerjaan Where no_anggota = @no_anggota";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Parameters.AddWithValue("@no_anggota", anggota.no_anggota);
                sqlCmd.Parameters.AddWithValue("@nama_ang", anggota.nama_ang);
                sqlCmd.Parameters.AddWithValue("@alamat", anggota.alamat);
                sqlCmd.Parameters.AddWithValue("@kota", anggota.kota);
                sqlCmd.Parameters.AddWithValue("@no_telp", anggota.no_telp);
                sqlCmd.Parameters.AddWithValue("@pekerjaan", anggota.pekerjaan);
                sqlCmd.Parameters.AddWithValue("@no_simp", anggota.no_simp);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // GET: Anggota/Delete/5
        public ActionResult Delete(string id)
        {
            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            using (SqlConnection sqlcon = new SqlConnection(connectionString))
            {

                string query = "DELETE FROM anggota Where no_anggota = @no_anggota";
                SqlCommand sqlCmd = new SqlCommand(query, sqlcon);
                sqlCmd.Connection.Open();
                sqlCmd.Parameters.AddWithValue("@no_anggota", id);
                sqlCmd.ExecuteNonQuery();
            }

            return RedirectToAction("Index");
        }

        // POST: Anggota/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Koperasi Simpan Pinjam/adminlte/Views/Anggota/Create.cshtml
@model adminlte.Models.AnggotaModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Tambah Anggota
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Data Master</a></li>
            <li class="active">Form Anggota</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "help - block" })


                            <div class="form-group">
                                <label>Nama Anggota</label>
                                @Html.EditorFor(model => model.nama_ang, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nama_ang, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Alamat</label>
                                    @Html.EditorFor(model => model.alamat, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Kota</label>
                                @Html.EditorFor(model => model.kota, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kota, "", new { @class = "help-block" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Nomor Telepon</label>
                                @Html.EditorFor(model => model.no_telp, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.no_telp, "", new { @class = "help - block" })
                            </div>

                            <div class="form-group">
                                <label>Pekerjaan</label>
                                @Html.EditorFor(model => model.pekerjaan, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.pekerjaan, "", new { @class = "help-block" })
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Tambah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

Koperasi Simpan Pinjam/adminlte/Views/Anggota/Edit.cshtml
@model adminlte.Models.AnggotaModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
  <!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Form Ubah Anggota
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Data Master</a></li>
            <li class="active">Form Anggota</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- SELECT2 EXAMPLE -->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Data</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-8">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.no_anggota)
                            @Html.HiddenFor(model => model.no_simp)

                            <div class="form-group">
                                <label>Nama Anggota</label>
                                @Html.EditorFor(model => model.nama_ang, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nama_ang, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Alamat</label>
                                @Html.EditorFor(model => model.alamat, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Kota</label>
                                @Html.EditorFor(model => model.kota, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.kota, "", new { @class = "text-danger" })
                            </div>
                            <!-- /.form-group -->
                            <!-- /.form-group -->
                            <div class="form-group">
                                <label>Nomor Telepon</label>
                                @Html.EditorFor(model => model.no_telp, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.no_telp, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>Pekerjaan</label>
                                @Html.EditorFor(model => model.pekerjaan, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.pekerjaan, "", new { @class = "text-danger" })
                            </div>

                            <!-- /.form-group -->

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Ubah" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.box-body -->

            </div>
        <!-- /.box -->
        }
    </section>

</div>

Koperasi Simpan Pinjam/adminlte/Views/Anggota/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Data Anggota
            <small>Koperasi Simpan Pinjam</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Data Master</a></li>
            <li class="active">Anggota</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <i class="fa fa-user-circle bg-blue"></i><h3 class="box-title">Anggota</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nomor Anggota</th>
                                    <th>Nama Anggota</th>
                                    <th>Alamat</th>
                                    <th>Kota</th>
                                    <th>Nomor Telepon</th>
                                    <th>Pekerjaan</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if(Model.Rows.Count == 0){
                                     <tr>
                                         <td>#</td>
                                         <td>#</td>
                                         <td>#</td>
                                         <td>#</td>
                                         <td>#</td>
                                         <td>#</td>
                                         <td>#</td>
                                     </tr>
                                }
                                else{
                                    for (int i = 0; i < Model.Rows.Count; i++)
                                    {
                                        using (Html.BeginForm("Delete", "RepFilters", new { @id = Model.Rows[i][0] }))
                                        {
                                            var myModal = "myModal" + Model.Rows[i][0];
                                            <tr>
                                                <td>@Model.Rows[i][0]</td>
                                                <td>@Model.Rows[i][1]</td>
                                                <td>@Model.Rows[i][2]</td>
                                                <td>@Model.Rows[i][3]</td>
                                                <td>@Model.Rows[i][4]</td>
                                                <td>@Model.Rows[i][5]</td>
                                                <td>
                                                    <a href="@Url.Action("Edit", "Anggota", new { @id = Model.Rows[i][0] })" class="btn btn-app btn-xs bg-blue"><i class="fa fa-edit"></i>Ubah</a>
                                                    <a href="" class="btn btn-app btn-xs bg-red" data-toggle="modal" data-target="#@myModal" data-whatever="@Model.Rows[i][0]"><i class="fa fa-trash"></i>Hapus</a>

                                                    <div class="modal fade" id="@myModal">
                                                        <div class="modal-dialog">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                    <h4 class="modal-title">Alert Modal</h4>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <p>Apakah anda yakin untuk menghapus data @Model.Rows[i][0]?</p>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Tidak</button>
                                                                    <a href="@Url.Action("Delete", "Anggota", new { @id = Model.Rows[i][0] })" class="btn btn-primary">Ya</a>
                                                                </div>
                                                            </div>
                                                            <!-- /.modal-content -->
                                                        </div>
                                                        <!-- /.modal-dialog -->
                                                    </div>
                                                    <!-- /.modal -->
                                                </td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                        <a href="@Url.Action("Create", "Anggota")" class="btn btn-success">Tambah Data</a>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
</div>

@section Scripts
{
    <script type="text/javascript">
  $(document).ready(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
    </script>

}